version: '3'
services:
  churierpweb-db:
    image: postgres:latest
    volumes:
      - churierpweb-db-volume:/var/lib/postgresql/data
    ports:
      - 6969:5432
    expose:
      - "5432"
    environment:
      POSTGRES_DB: churierpweb
      POSTGRES_USER: churierpweb
      POSTGRES_PASSWORD: angel7
      PGDATA: /var/lib/postgresql/data/pgdata
    networks:
      - churinet
  churierp:
#TODO parameterize version
    image: org.bastanchu/churierpweb:0.1
    restart: unless-stopped
    depends_on:
      churierpweb-db:
        condition: service_started
    ports:
      - 8888:8080
    environment:
      JDBC_URL: jdbc:postgresql://churierpweb-db:5432/churierpweb
      JDBC_USERNAME: churierpweb
      JDBC_PASSWORD: angel7
    networks:
      - churinet
#Volumes
volumes:
  churierpweb-db-volume:
#Network configuration
networks:
  churinet:
    driver: bridge
#Execute these steps in the same directory where docker-compose.yaml is
#Step 1 verification
#docker compose config
#Step 2
#docker compose build
#Step 3 to run
#docker compose up -d
#Step 4 to stop
#docker compose down