version: '2.2'
services:
  postgres:
    image: postgres:10.5
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '18800:5432'
    volumes:
      #- ./postgres-data:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ./sql:/docker-entrypoint-initdb.d